name: instagramz_clone
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated Direct Dependencies
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  font_awesome_flutter: ^10.8.0
  image: ^4.3.0
  image_picker: ^1.1.2
  video_thumbnail: ^0.5.3
  video_player: ^2.9.2
  lottie: ^3.1.3
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  riverpod_annotation: ^2.6.1
  intl: ^0.20.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updated Dev Dependencies
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1

flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json

  # Fonts (Unchanged)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Dependency Overrides to Address Security Advisories
dependency_overrides:
  archive: ^3.6.1
