// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6V-ue92DppNaYVwPQkgt6P6mJNmHHd1Y',
    appId: '1:627311697824:android:cef263cb6cd48beb2c4ec5',
    messagingSenderId: '627311697824',
    projectId: 'petstagram-7a254',
    storageBucket: 'petstagram-7a254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfZnf8rbyBcDIRZWLy3N2okefSizb_G0o',
    appId: '1:627311697824:ios:ebd9ca9cb117b2642c4ec5',
    messagingSenderId: '627311697824',
    projectId: 'petstagram-7a254',
    storageBucket: 'petstagram-7a254.firebasestorage.app',
    iosBundleId: 'se.uzoebubes.instagramzClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0u1xl8X0wvgZxN7hpqSAyDPCxv4ttqpU',
    appId: '1:627311697824:web:3129d517326d20772c4ec5',
    messagingSenderId: '627311697824',
    projectId: 'petstagram-7a254',
    authDomain: 'petstagram-7a254.firebaseapp.com',
    storageBucket: 'petstagram-7a254.firebasestorage.app',
    measurementId: 'G-QWW62FSER0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfZnf8rbyBcDIRZWLy3N2okefSizb_G0o',
    appId: '1:627311697824:ios:ebd9ca9cb117b2642c4ec5',
    messagingSenderId: '627311697824',
    projectId: 'petstagram-7a254',
    storageBucket: 'petstagram-7a254.firebasestorage.app',
    iosBundleId: 'se.uzoebubes.instagramzClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0u1xl8X0wvgZxN7hpqSAyDPCxv4ttqpU',
    appId: '1:627311697824:web:eee32e874dbe894c2c4ec5',
    messagingSenderId: '627311697824',
    projectId: 'petstagram-7a254',
    authDomain: 'petstagram-7a254.firebaseapp.com',
    storageBucket: 'petstagram-7a254.firebasestorage.app',
    measurementId: 'G-8TCTRD15Z1',
  );

}